# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "7d34db6e32ec25e76202713215f8607a"
name = "validation-extension"
handle = "validation-extension-1"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
dev_store_url = "ivan-checkout.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
